see #2078 added verbose error message in a situation when "ifconfig carp0 create" command fails to create CARP interface.

diff --git a/src/res/configlets/bsd/update_carp b/src/res/configlets/bsd/update_carp
--- a/src/res/configlets/bsd/update_carp
+++ b/src/res/configlets/bsd/update_carp
@@ -42,7 +42,10 @@ sync_carp_interfaces() {
         $IFCONFIG $intf >/dev/null 2>&1 || {
             echo "# Creating carp interface $intf"
             $SYSCTL -w net.inet.carp.allow=1
-            $FWBDEBUG $IFCONFIG $intf create
+            $FWBDEBUG $IFCONFIG $intf create || {
+                echo "Error: CARP interface $intf could not be created. Does the kernel have CARP enabled?"
+                exit 1
+            }
         }
     done
 }
